name: 'B&B Commercial Cleaning'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9495730940252542
title: 'B&B Commercial Cleaning Services'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72854164-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#838383'
    - '#4f4f4f'
    - '#b7b7b7'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
