name: 'B&B Commercial Cleaning'
favicon: null
layout_spectrum: 0.2369049594271928
typography_spectrum: 0.9495730940252542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5532118785195053
  lightness: 0.023541806265711784
  saturation: 0.10063821822404861
  rhythmicContrast: 0.8498722806107253
purpose: []
